# Let's upload reprox to PyPi to make it pip installable
# Mostly based on https://github.com/marketplace/actions/pypi-publish
name: Pipy
on:
  push:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ "ubuntu-latest" , "macos-latest", "macos-10"]
    steps:
      # Setup steps
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install wheel twine
      - name: Build weels (linux)
        if: matrix.os == 'ubuntu-latest'
        uses: RalfG/python-wheels-manylinux-build@v0.4.2-manylinux2014_x86_64
        with:
          python-versions: 'cp36-cp36m cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
          build-requirements: 'cython numpy'
      - name: Publish wheels to PyPI (linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run: |
          twine upload dist/*-manylinux*.whl

      - name: Build package (MAC)
        if: matrix.os != 'ubuntu-latest'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
        run:
          |
          pip install twine
          python setup.py bdist_wheel
          python -m twine upload -u "${TWINE_USERNAME}" -p "${TWINE_PASSWORD}" dist/*;
